name: money_transfer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/p1.jpg
    - assets/images/p2.jpg
    - assets/images/p3.jpg
    - assets/images/p4.jpg
    - assets/images/p5.jpg
    - assets/images/p6.jpeg
    - assets/images/p7.jpeg
    - assets/images/p7.jpg
    - assets/images/p8.jpg
    - assets/images/p9.jpeg
    - assets/images/p10.jpg
    - assets/images/p11.jpeg
    - assets/images/p12.jpg
    - assets/images/p13.jpg
    - assets/images/less.png
    - assets/images/favorite.png
    - assets/images/favorite_active.png
    - assets/images/money.png
    - assets/images/money_1.png
    - assets/images/money_2.png
    - assets/images/money_3.png
    - assets/images/money_transfer.png
    - assets/images/money_transfer1.png
    - assets/images/request.png
    - assets/images/venmo.jpg
    - assets/images/venmo1.jpg
    - assets/images/venmo2.jpg
    - assets/images/venmo3.png
    - assets/data/feed.json
    - assets/data/recent.json
    - assets/data/all_contact.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
